### ISSUE TITLE
Enharmonic chords cause exception to be raised

### ISSUE THREAD

**Issue by stufro** [stufro/chordly#2]
If you enter an enharmonic chord (e.g. E#) into a chord sheet and attempt to transpose it, the following exception is raised:

```
NoMethodError (undefined method `-' for nil:NilClass

        (index2 - index1) + ((octave2.to_i - octave1.to_i) * NOTES.size)
                ^):
  
app/models/chord.rb:30:in `new'
app/models/chord.rb:30:in `transpose_note'
app/models/chord.rb:21:in `transpose'
app/models/sheet_line.rb:16:in `block in transpose'
app/models/sheet_line.rb:14:in `each'
app/models/sheet_line.rb:14:in `transpose'
app/models/chord_sheet.rb:12:in `block in transpose'
app/models/chord_sheet.rb:8:in `map!'
app/models/chord_sheet.rb:8:in `transpose'
app/controllers/chord_sheets_controller.rb:36:in `transpose'
```

The root of this error appears to be un the music gem here: https://github.com/cheerfulstoic/music/blob/master/lib/music/note.rb#L279

**Comment by stufro** [comment]
Fixed in [v0.2.1](https://github.com/stufro/chordly/releases/tag/v0.2.1)
